services:
  - type: web
    name: kms-community-library
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://librarymanagementsystem-1-tu42.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: kms-library-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kms-library-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: kms-library-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: kms-library-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kms-library-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: LOG_CHANNEL
        value: stack
    plan: free
    autoDeploy: true

databases:
  - name: kms-library-db
    plan: free
    databaseName: library_management
